#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class TextBox;
                ref class Button;
                ref class RadioButton;
                ref class TextBlock;
            }
        }
    }
}

namespace NativeMathSDKSample
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::TextBox^ FirstNumber;
        private: ::Windows::UI::Xaml::Controls::TextBox^ SecondNumber;
        private: ::Windows::UI::Xaml::Controls::Button^ Execute;
        private: ::Windows::UI::Xaml::Controls::RadioButton^ add;
        private: ::Windows::UI::Xaml::Controls::RadioButton^ subtract;
        private: ::Windows::UI::Xaml::Controls::RadioButton^ multiplyWRT;
        private: ::Windows::UI::Xaml::Controls::RadioButton^ divideWRT;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ resultText;
    };
}

